### ISSUE TITLE
Using my own glottolog tree

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#102]
In the future, I may want to use my own pseudo-glottolog tree, in particular while suggested changes to the tree from colleagues have made it to me, but not into a glottolog release yet.

Do I see it correctly that the current way to do this is to drop the Newick file, geo data csv etc. in `beastling/data/` as `glottolog-2.7-leiden-patch.newick` etc. and tell `beastling` in the config to use

```
glottolog_release=2.7-leiden-patch
```

and do I see correctly that this is a semi-robust way to specify this, that it will not break or hamper other things, and that we might want to document it and make it explicit?

**Comment by lmaurits** [comment]
Are you talking about supplying an alternative set of monophyly constraints and language locations, different from Glottologs?  If so, the "official" (but undocumented, because I'm naughty) method to do this is:

```
[languages]
monophyly_newick = "/path/to/glottolog-2.7-leiden-patch.newick"
location_data = "/path/to/locations-leiden.csv"
```

(or instead of a path I believe you can just put the newick tree directly in the config file if it's a small dataset).  BEASTling will prune the supplied tree down to match the taxa in your analysis and use it as the monophyly constraint, instead of Glottolog's.  Redundant nodes will be removed but polytomies will not be resolved.  Duplicate taxa or missing taxa from the analysis should throw an error.  The `location_data` file (which must be a file), should look like this:

```
iso, lat, lon
aiw, 5.95, 36.57
aas, -4.01, 36.86
kbt, -9.03, 146.99
abg, -6.12, 145.66
abf, 5.55, 118.31
```

Actually, the code handling that should be tidied up a little bit, the header is currently completely ignored and the rows _must_ be in the order iso (or glotto), latitude, longitude.

It would actually be great to hear back if you get this working in the way you want, I have used it for some of my analyses but not tested too extensively.

**Comment by Anaphory** [comment]
I was more thinking of starting tree and location data. The reason I thought of (ab)using `glottolog_release` is that I do want to feed the underlying information back into glottolog, and I thought I might as well use the tree I get out of my local glottolog.

It's likely an impractical idea, because I need to modify the starting tree anyway, because it encompasses two families. I will therefore have to specify the starting tree in a separate newick file anyway.

That leaves the location data, and for specifying one file your approach sounds much better than abusing the release field.

**Comment by Anaphory** [comment]
I have split the documentation issue and consider the other originally requested features not worth supplying, for the reasons discussed above.
