### ISSUE TITLE
Tutorial: Make sampling from prior an integral part of the learning experience

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#105]
Instead of a final remark at the end of the tutorial, where much of the audience will have already left to play with simpler models of Beastling, make sampling from prior integral part of the process we teach people, from the first Beast run (or actually, before! Priors should be known before integrating data) onwards.

**Comment by Anaphory** [comment]
This is partially solved in #127, but there are still gaps where I blagged that something should be visible in the prior log (but haven't properly checked), one place where I want to give a value from the log but haven't calculated it yet, and in the very last bit with calibrations, it would be really good to show what the prior does and generate a summary tree.

**Comment by lmaurits** [comment]
This is the last remaining Issue tagged for 1.4.0 not related to ASR (woohoo!).  I'm happy to spend some time on it this week, but can we decide first a little more clearly what it is we want to achieve?  I'm all for educating our users about best practice, but at the end of the day the tutorial should be about learning how to use the software and I don't want to scare folks off by putting some "mad statistician's diatribe" right at the front.

**Comment by Anaphory** [comment]
What I envision is just a short subsection towards the end when the tutorial is wrapping up, saying something like

> Of course, to understand how expressive our data is, we need to compare how much the properties of the posterior distribution, which we inferred using that data, differ from the prior distribution. The prior is not easy to inspect, but we can simply sample it, and get outputfiles of exactly the same shape as the posterior, so we can easily analyse them with the same tools and compare the results.
Beastling makes this sampling from prior very easy: …

**Comment by lmaurits** [comment]
I tried to make a start on this yesterday.  It seems like your commit earlier this year did a really good job of diffusing discussion of the prior issue all throughout.  But there were some stubs at the end of the calibration section.  I tired sampling from the prior for that config so I could put in some details on the prior distribution over the root age and also show the summary tree, however ran into problems.

When you only place a single calibration, we try to "do the right thing" and use the calibrated version of the Yule prior.  The problem is that this acts a little oddly when there is no data to constrain it.

If you run with the regular prior, it acts exactly how you would expect - the fact that we have a constraint on Romance restricts the birthrate parameter to some interval which is broadly compatible with that constraint, and then the root age is in turn restricted to some interval compatible with that birthrate.

However, with the calibrated version of the prior, the Yule process is _conditioned_ on the fact that Romance is such-and-such an age, so this can't actually inform the birthrate, and it tends to escape to ludicrous values, resulting in ludicriously low prior tree ages.

The quick and dirty solution would be not to emit the conditioned Yule when sampling from the prior, even if we otherwise would, but I'm not sure I'm comfortable having the `--prior` flag actually change the XML beyond inserting the `sampleFromPrior=True`.

Alternatives are dropping the calibrated Yule outright, or else avoiding silly values of the birthrate by either restricting the domain of that parameter or putting some kind of generic prior on it.  I have actually been thinking about the latter for a while.  It's not hard to figure out, from language family sizes and rough estimates of age (e.g. from that ASJP paper) what the sensible range of birthrates is, we could put an upper limit of 10 times the highest sensible birthrate, which would at least prevent run aways to infinity.  The problem is this is all scale dependent, i.e. the range of sensible birthrates depends on whether your branch lengths are in years, centuries or millenia, and it's kind of nice to remain agnostic on that.

**Comment by lmaurits** [comment]
Maybe the simplest fix here (i.e. that involving no changes to the behaviour of BEASTling) would be to put _two_ (non-nested) calibration points into the analysis.  This will disable the calibrated Yule and things should behave themselves.  What's a calibration we can use for proto-Germanic which passes the laugh test?

**Comment by lmaurits** [comment]
Looks like this is the only 1.4.0 Issue left!  I'll see if I can close this today.

**Comment by lmaurits** [comment]
Okay, not going to close this today, but I have the final tutorial analysis running now and will close this this week sometime.  I ended up going with the two calibrations in order to sidestep the weird Yule prior issue.

**Comment by lmaurits** [comment]
Alright, the calibration section is now much extended with a lot of focus on sampling from the prior and comparing the results to the posterior.  Surely there is still more that could be said, but we are giving the issue more attention than we used to, and one must draw the line somewhere or the tutorial will end up turning into a book.

@Anaphory you have some fancy automated testing that is done on the tutorial, right?

**Comment by Anaphory** [comment]
I think I wrote `scriptdoctest` for that purpose, yes? I'll have a look.

**Comment by Anaphory** [comment]
`scriptdoctest` says the tutorial is fine now.
