### ISSUE TITLE
Models are hard-coded in configuration.py

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#11]
There is a finite list of models listed in `configuration.py`, so anyone (like me) wishing to add another model to the list has to not just write a new module for the model, but also add two lines to `configuration.py`.

Making use of python's basic introspection and interpretation capabilities (such as `dir` and some kind of safer `__import__` or `eval`), this need could be removed, and it would even be possible to specify any `Model` class, which could be defined in a separate package (or in `pwd`), to provide the model logic through the configuration file.

**Comment by lmaurits** [comment]
I have wondered about how to deal with this.  My expectation was that other people would write and publish BEAST packages, and if I liked the look of one I would write my own BEASTling BaseModel subclass for it and do a new BEASTling release.  But I suppose I should not discourage third parties from doing this work for me too!  I will look into the safest way to allow importing arbitrary model classes.

**Comment by Anaphory** [comment]
It looks to me like it is reasonable to assume that every new model will be described by a single `BaseModel` subclass living in a separate module.

If you can assume that the class is called `Model`, you should easily be able to do 

```
            else:
                try:
                    model = __import__(config["model"]).Model(config, self)
                except (ImportError, AttributeError):
                    raise ValueError("Model '%s' for model section '%s' could not be generated." % (config["model"], config["name"]))
```

_Pros:_ This is very simple, my new model specification does not even have to live in `beastling/models/`. It makes it very easy to use all modules under `beastling/models/` with a few lines of very generic code.
_Cons:_ To be consistent with this, all models would have the same class name `Model`, which can turn into a pain when debugging at 3am. `getattr()` would allow a workaround of constructing a name different from `Model` and accessing it.

**Comment by xrotwang** [comment]
I think rather than assuming a fixed class name, one could just loop over the import objects and pick the one that's class derived from `BaseModel`.

But in the long run - i.e. when more code-like things should be configurable, a full-fledged plugin system may be a better fit. I quite like the [Zope Component Architecture](http://muthukadan.net/docs/zca.html), but it may be a bit heavy-weight here.

**Comment by lmaurits** [comment]
I've pushed the following first pass at this:

```
            else:
                try:
                    sys.path.insert(0, os.getcwd())
                    module_path, class_name = config["model"].rsplit(".",1)
                    module = importlib.import_module(module_path)
                    UserClass = getattr(module, class_name)
                    model = UserClass(config, self)
                except:
                    raise ValueError("Unknown model type '%s' for model section '%s', and failed to import a third-party model." % (config["model"], config["name"]))
```

The usage is that you supply in the config file both a package/module and a class name, e.g.:

```
[model mymodel]
model = foo.bar.AwesomeModel
```

Importing from the cwd where `beastling` is run is supported (this facilitates easily distributing a BEASTling .conf file and the required Python modules to make it work).

I think this is a good solution because:
- It does not require all models to have the same class name, which could easily get confusing
- It permits defining multiple substitution model classes in a single Python module
- It takes a Pythonic "duck typing" approach (a model class need not necessarily subclass BaseModel)

However, I freely admit that I am extremely inexperienced with Python's dynamic importing, introspection and all that jazz, so if I am overlooking some horrible shortcoming with this implementation, please shout out.

Oh, by the way, the models distributed with BEASTling (covarion, mk and bsvs) are all still recognisable by those names - I don't want to force users to write `beastling.models.mk.MKModel`.  This results in more code but I think it's more than worth it from a usability standpoint.

**Comment by Anaphory** [comment]
This looks like a good way to do it! Apart from the fact that I cannot just drop a new module in `models/` and expect it to work with a short name, I like it even much better than what I was starting to write.

**Comment by Anaphory** [comment]
Oh, the additional code could as well just come down to specifiyng `aliases = {'mk': 'beastling.mojels.mk.MKModel', ...}` and replacing `module_path, class_name = config["model"].rsplit(".",1)` by

```
 model = aliases.get(config["model"], config["model"])
 module_path, class_name = model.rsplit(".",1)
```

or similar.

**Comment by xrotwang** [comment]
It may be worth using the [dotted name notation](http://docs.pylonsproject.org/projects/pyramid/en/latest/glossary.html#term-dotted-python-name),
i.e. separate the class name with a colon. The advantage would be that we
can link to the pyramid docs as explanation, and maybe even reuse their
DottedNameResolver.
Am 11.03.2016 22:03 schrieb "Luke Maurits" notifications@github.com:

**Comment by lmaurits** [comment]
Is this notation widely used outside of Pyramid/Pylon?  Without a better argument, I am not too enthusiastic.  I can see it's value for a more general purpose application, where you can use `foo.bar.baz:MyClass.my_method` and it's not ambiguous where the package/module ends and the class begins.  But for our application, where the user must specify a class only, this advantage does not apply.  Instead, we only get the disadvantage that our notation is different from the notation people are already familiar with for referring to imported classes.

**Comment by xrotwang** [comment]
@lmaurits  You are right, the ':' notation is optional, though. I just came across a package [`dotted_name_resolver`](https://pypi.python.org/pypi/dotted_name_resolver/0.0), which lifts the relevant functionality out of pyramid. Maybe this would be an acceptable dependency. It actually comes with another piece of potentially interesting functionality: `AssetResolver`, a mechanism to resolve paths to data files in python packages. This may be an elegant way to use and distribute additional data packages for BEASTling.

**Comment by lmaurits** [comment]
I am happy to keep this package in mind for future use if a good need for it arises, but as it stands I think that adding another dependency to replace this one fairly small and simple block of code, which is only used in one place and appears to work well, is a bit hard to justify.

Now that I think of it, I suppose there is no good reason we should not accept the specification of third party classes for clock models, right?
