### ISSUE TITLE
Supplying monophylies and locations is possible but undocumented

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#129]
As stated in #102:
> supplying an alternative set of monophyly constraints and language locations, different from Glottologs?  If so, the "official" (but undocumented, because I'm naughty) method to do this is:
> 
> ```
> [languages]
> monophyly_newick = "/path/to/glottolog-2.7-leiden-patch.newick"
> location_data = "/path/to/locations-leiden.csv"
> ```

**Comment by lmaurits** [comment]
I was going to document `location_data` at the same time as documenting `[geography]` earlier this morning, but realised with some dismay that `location_data` actually belongs to `[languages]`.  What was I thinking with that?!

**Comment by Anaphory** [comment]
I think that may have happened before the `[geography]` section came to be and is probably a thing that should be cleaned up.

   [geography]
   data=…

in analogy with other model specifications? Making that backwards-compatible may be some effort.

**Comment by lmaurits** [comment]
Yeah, backward compatibility is the big gotcha here.  It may not be too bad, for a while we can let it be specified in either section but emit a loud deprecation warning if ti is in [language] and not [geography], and then eventually require it only in geography.

**Comment by lmaurits** [comment]
Okay, you can now do `[geography] data=`, and when using BEASTling from the command line and trying to use `[languages] location_data=` you will see a deprecation warning on `stderr`, even if you have not used `--verbose` (achieved by putting the warning in `Configuration.urgent_messages` instead of `Configuration.messages`).  Let's continue to load the old way for 1.4.x and 1.5.x but then remove support.

This means I can finally document this without feeling ridiculous for having the geographic documentation spread across multiple sections of the docs!  So this issue will be closed sometime very soon.

**Comment by lmaurits** [comment]
Done at last!
