### ISSUE TITLE
Test whether reconstruction generates the expected file types

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#172]
Reconstruction should be available soon, but at the moment we just check whether the analysis runs. It would be useful to also check whether the expected files are generated – will this need a slight restructuring of how tests are run, to separate the outputs of different tests?

**Comment by lmaurits** [comment]
It looks like this wouldn't be too hard to do.  My first instinct is to hack the `_do_test` function in `beastrun_tests.py` to take an optional second argument which is some kind of "result inspecting function".  That function could be passed the temporary directory that the test was run in (you can copy this from the `cwd` argument to `check_call`) and can then parse the output files to its heart's content and `assert` various things along the way.  Instead of putting the ASR tests in the big long list of tests done here, do it by itself in a separate test and pass in your result inspector.

We should probably do more of this sort of thing when addressing #117, so as part of 1.5's restructuring we can make it much easier / less clunky to do these kind of tests.  But for now I'm happy to leave this in `beastrun_tests.py`.

**Comment by Anaphory** [comment]
And the default for that function would be `lambda tmpdir: None` for backward compatibility. Sounds good, I'll have a look at that.

**Comment by Anaphory** [comment]
It does require, though, that tests clean up after themselves, or each gets their own directory. Otherwise we might get strange interactions between the result inspecting functions of different tests and what they expect might be there.

I'll take a naïve approach that assumes interactions will never really be harmful for now, but please let us discuss what a *good* solution would look like at some point.

**Comment by Anaphory** [comment]
Yes, closed by #176
