### ISSUE TITLE
Not sampling branch lengths but calibrating tips

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#189]
I just noticed that when I deactivate sampling branch lengths, tips with non-fix calibration still move about, but they are not logged anywhere. What *should* be the behaviour?

I expected tips not to move.
I could see arguments for tips moving, but then they should be logged somewhere.

(As a side note, do fixed calibrations trump starting tree tip heights? Should there be a warning if they don't match, in particular for fixed branch lengths?)

**Comment by lmaurits** [comment]
I think the behaviour should be exactly as you expected, that tips not move (i.e. that length of their incoming branches not be sampled).  This should be an easy fix, we just didn't think of this interaction when we added the tip sampling stuff.

I think right now if you provide a starting tree which is inconsistent with a calibration then BEASTling will run fine but BEAST will not start the resulting analysis due to not being able to find a starting state with finite initial prior probability.  This is exactly the same situation as starting trees which violate monophyly constraints.  Ideally in both cases BEASTling would notice this and complain fatally.

**Comment by lmaurits** [comment]
Should work as expected now?

**Comment by Anaphory** [comment]
Does.
