### ISSUE TITLE
Covarion model estimates global frequencies for all partitions.

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#199]
Running a binary covarion model for lexical data with estimated frequencies, I noticed that the visible frequencies are estimated for all meaning slots together, instead of each meaning slot separately.

I would expect those frequencies to differ widely by concept, a concept with only two different cognate sets should have visible frequencies of roughly (0.5, 0.5), while a very instable concept with 20 different cognate classes should probably have something like (0.95, 0.05).

Am I thinking correctly in principle? Are there nonetheless reasons (computation time, numerical stability, model complexity etc.) why we might want to keep the behaviour as it is?

**Comment by lmaurits** [comment]
By setting `share_params = False` in your config you should be able to estimate per-meaning slot covarion parameters.

I agree that some variation in these seems reasonable.  I think the default is to share one set of parameters for all meaning slots just because that's how it was done in at least one of the big IE papers, and probably also in whatever working sample of the model I was shown when I first implemented this.  It's also how Babel does things, IIRC.

I'm not aware of any stability issues around this, but computation time and model complexity/identifiability might be concerns.

Feel free to experiment!
