### ISSUE TITLE
Advanced clock handling

### ISSUE THREAD

**Issue by lmaurits** [lmaurits/BEASTling#43]
In addition to the current strict clock models, BEASTling should support uncorrelated relaxed clocks (in Exponential and Lognormal forms) and random local clocks.  It should also be possible to specify different clocks of different types for different datasets.  This is obviously going to involve overhauling the configuration format somewhat.

The most straightforward thing seems to be to add [clock <name>] sections, similar to how we currently have [model <name>] sections.  Options within these sections can specify the kind of clock (strict, relaxed, random) and associated parameters.  Models can specify which of the instantiated clocks to use with a "clock=" option, which refers to clocks by name.

Right now, the specification of clocks is entirely implicit, and each [model] section gets its own strict clock.  For the sake of backward compatibility, we should leave this as is.  However, as soon as a single [clock] section is introduced, we basically have free reign for defining new behaviour.  One thing that I think would be nice is that if only a single [clock] section is specified, then that clock gets associated with _all_ [model] sections, unless those sections have their own "clock=" option within them overriding this.  This results in the minimum number of config lines for what I assume will be the most common situation (one clock shared across all models).

@xrotwang @Anaphory @SimonGreenhill Does this sound sensible to people?

**Comment by xrotwang** [comment]
I think in terms of config file syntax that's fine, in particular since it mimics the [python logging config file format](https://docs.python.org/2/library/logging.config.html#configuration-file-format). The latter has explicit sections `[loggers]`, etc. listing all names for objects of a type, before specifying config options for them, but I'm not really sure what this would add.

I see one problem, though, with the idea to associate a clock - if only one is specified - with all models by default. Since there is an implicit default clock as well, it doesn't seem obvious to me, that **one** explicitly configured clock will override the implicit default. To safeguard against this, we could treat the implicit default clock like python does with the root logger: Distinguish it with a special name. So if **one** clock is configured using the section name `clock_default`, this could override the implicit default, whereas **one** clock section with a different name will lead to two clocks being available for reference in model sections.

**Comment by lmaurits** [comment]
I agree this is perhaps not super obvious, however, I'm also not the fan of the (only, it seems to me) alternative.  If a user specifies one [clock myclock] section, but makes no explicit "clock=myclock" settings in any of their [model] sections, and we retain the behaviour of giving each [model] its own separate strict clock, then the [clock myclock] section is essentially completely ignored.  I feel like, for the average intended user, who is not necessarily someone with years of experience using precisely-parsed textual configs, this violates the principle of least surprise - "stupid BEASTling, I wrote a [clock] section, isn't it obvious I want to use it?!".

**Comment by Anaphory** [comment]
So why not do it the following way, because both your arguments are good:

Semantically, we parse as follows.
- If there is no `[clock default]` section, an implicit _strict_ `[clock default]` is created.
- If a model does not specify a clock, it uses the `default` clock, which is now either a strict clock or whatever `[clock default]` specified
- If a clock was specified, but not used in any model, warn the user, saying `Clock $(clock) was specified, but not used in any model.` If that was the only clock specified, add `Did you mean do specify a default clock using '[clock default]'?`

In the support, we additionally
- Ensure that clocks in examples we give have reasonable names, which either explicitly correspond to the model(s) they are for, or are called `default`. Never use `myclock`, use `clock_for_mymodel` instead if you must.

This means that, different from Luke's suggestion, combining two separate config files makes it obvious that the name `default` is a duplicate.

**Comment by SimonGreenhill** [comment]
Yes, what @Anaphory said.

**Comment by lmaurits** [comment]
> Ensure that clocks in examples we give have reasonable names, which either explicitly correspond to the model(s) they are for

What do we think of the idea that if the name of a clock exactly matches the name of a model, then they are automatically associated with one another?

**Comment by Anaphory** [comment]
Plus side: It saves a single line of configuration code.
Negative side: When you rename your model, you have to remember to also rename your clock, or weird stuff starts happening and the warning that the clock is unassociated may drown.

**Comment by lmaurits** [comment]
Hmm, good catch on the negative.  I still think it's a fair trade, but happy to hear other's opinions.

At any rate, I will implement the rest of the config details as you and Simon agree tomorrow.  Right now I have lognormal relaxed, exponential relaxed and Gamma random local clocks all minimally working, but I need to ask Remco some questions tomorrow on fine details, and also add a little more flexibility in the configuration.  Also, I suspect that the random local implementation is not compatible with Joseph's pruned tree class at the moment, I need to ask him that tomorrow too.  Still hoping to have the clock stuff completed by the end of this week, though.

**Comment by SimonGreenhill** [comment]
Personally, too much magic is a bad thing. Better to be explicit rather than implicit.

**Comment by lmaurits** [comment]
I take off my robe and wizard hat...

**Comment by xrotwang** [comment]
Well documented magic may be ok, though :)
I think that minimal number of config lines is an important design goal, because as it stands now, configs which fit on one screen seem to be in reach, which is half way to fitting it all in your head.

**Comment by lmaurits** [comment]
Okay, I have merged my "clocks" branch with develop, as most of the work is done now and tests are passing.  Config works as described by @Anaphory, but I have included the name-matching magic for now, as I agree with @xrotwang that concise configuration should be an important goal and it seems unlikely to cause too many problems.

The docs still need to be updated, I'll have that done by the end of the week.  I also need to give power users the ability to be a bit more specific about distributions and such.  But, for now, the three new models should all basically work in the usual way - the mean rate will be fixed to 1.0 if the tree is arbitrarily rescalable, and will be inferred if not.  No guarantees yet and testing welcome!
