### ISSUE TITLE
Beast maximum chain length is 2^32

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#47]
Beast stores chain length in an int, so its maximum value is 2^32 (maybe -1 or /2, for signs and zeros)
We should not permit bigger chain lengths to be written to xml, at least not without a warning.

**Comment by lmaurits** [comment]
Did you find this out by trying to specify such an analysis?!

I think the appropriate response to this is to have BEASTling replace longer chain lengths with BEAST's maximum and emit a warning.  This seems better to me than simply warning and producing an XML which will not run.

Or do these XMLs run, but BEAST interprets the chain length modulo 2^32 or something, so that what was supposed to be a very long chain may be very short?

**Comment by Anaphory** [comment]
They do not run, the parser that tries to parse chainLength="10000000000" fails and Beast exits.
Your suggestion of setting it to the max and warning sounds right.

**Comment by lmaurits** [comment]
It was /2, by the way, so must be a signed int.
