### ISSUE TITLE
Error running BEAST 2.3.1 with xml created from tests/configs/basic.con

### ISSUE THREAD

**Issue by xrotwang** [lmaurits/BEASTling#5]
I created a BEAST XML file running

```
beastling tests/configs/basic.conf 
```

but BEAST 2.3.1 chokes on it, reporting:

```
Cannot create class: LewisMK. Class could not be found. Did you mean beast.core.Logger?

Error detected about here:
  <beast>
      <run id='mcmc' spec='MCMC'>
          <distribution id='posterior' spec='util.CompoundDistribution'>
              <distribution id='likelihood' spec='util.CompoundDistribution'>
                  <distribution id='traitedtreeLikelihood.model:f0' spec='TreeLikelihood'>
                      <siteModel id='geoSiteModel.model:f0' spec='SiteModel'>
                          <substModel id='mk.s:model:f0' spec='LewisMK'>
```

**Comment by lmaurits** [comment]
Hi Robert.  This is a bug in documentation, if anything.  The default substitution model in BEASTling is the Lewis Mk model (a generalisation of Jukes-Cantor).  This model is not included in the BEAST core, but rather is implemented in a package called MorphModels, which you will have to install ([managing packages](http://beast2.org/managing-packages/) is quite easy with Beauti).  It's probably well worth installing the BEAST_CLASSIC and BEASTlabs packages too, I think it's very easy to produce XMLs which depend upon those.

I do plan to update BEASTling so that whenever it generates a file it lists all required BEAST packages on stdout, to make it easier to recognise when this kind of thing happens.  And also to mention this more prominently in the documentation (which I am currently sprucing up and moving to readthedocs.org.

**Comment by xrotwang** [comment]
Ah yes, this did the trick.
