### ISSUE TITLE
A way to make docstring-like explanations of attributes accessible?

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#72]
If we stumble over a module that permits tying documentation to class attributes, we should see whether we can use it instead of strings that will be ignored, such as

```
    self.sample_branch_lengths = True
    """A boolean value, controlling whether or not to estimate tree branch lengths."""
```

**Comment by Anaphory** [comment]
Note that this lower than a “nice-to-have” feature in my mind – it has a very very niche applicability during development using an interactive print/eval-loop instead of looking through the source code.

I just expect that we are not the first people to try to document their attributes, so I expect a thin wrapper for it to exist, and if it does and we happen to encounter it, it may be worth considering here.

**Comment by lmaurits** [comment]
Those docstrings are there precisely because Sphinx either does or is supposed to recognise them and put them into automatically generated documentation of the class.  I forget right now if I have this working yet or not - Simon semi-recently got lots of Sphinx voodoo working which I had been struggling with.

**Comment by Anaphory** [comment]
Oh, cool!
