### ISSUE TITLE
Uncaught error for empty model section

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#73]
If the model section is empty, beastling throws

```
Error encountered while parsing configuration file:
Traceback (most recent call last):
  File "/home/gereon/python/beastling/cli.py", line 91, in do_generate
    config.process()
  File "/home/gereon/python/beastling/configuration.py", line 355, in process
    self.load_glotto_class()
  File "/home/gereon/python/beastling/configuration.py", line 395, in load_glotto_class
    name, glottocode, isocode = parse_label(node.name)
  File "/home/gereon/python/beastling/configuration.py", line 378, in parse_label
    label2name[label] = (match.group('name').strip().replace("\\'","'"), match.group('glottocode'))
AttributeError: 'NoneType' object has no attribute 'group'
```

instead of complaining that the model section is empty.

**Comment by Anaphory** [comment]
I still get that error also for a maybe well-specified beasting file, but:
Why are we parsing the whole set of glottolog trees independent of whether a config file needs any of those features?

**Comment by Anaphory** [comment]
My own bloody fault. I needed a hack of python-newick to support a nexus file with comments, and that managed to take out the glottolog labels, as well.
(confer https://github.com/glottobank/python-newick/issues/9)

**Comment by lmaurits** [comment]
> Why are we parsing the whole set of glottolog trees independent of whether a config file needs any of those features?

This has been on my radar for a little while.  After I refactored Configuration.process and BaseModel.process to have clean, clear, consistent code, BEASTling became noticeably slower and I don't really enjoy the user experience as much since this.  A lot of this is due to processing stuff before checking if it's necessary.  I would very much like to see this done smarter, just haven't gotten around to it yet.
