### ISSUE TITLE
Singletons in trees

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#75]
When pruning and de-polytomising a Newick tree, singleton internal nodes can result. This should not be an option in beastling.

See also https://github.com/glottobank/python-newick/issues/13

**Comment by lmaurits** [comment]
Looks like this has been dealt with upstream, can I close this or is there more to do on the BEASTling end of things?

**Comment by Anaphory** [comment]
Been out of this loop for a bit. I think it's fine now, but I'm not sure enough.

**Comment by Anaphory** [comment]
The thing to do on the Beastling side is to add some more detailed tests to `starting_tree_tests.py` to ensure that the constructions we work with are actually good. I'm working on that. I mean, those tests _should_ actually be in python-newick, but we can't just hand something to `newick`, get anything back and ignore what we got back.

In particular, `starting_tree_tests.py` builds configs and parses them, can we tie those into the `beastrun` tests? That would have flagged my current issue much earlier, because the truncated trees make Beast fail.

**Comment by lmaurits** [comment]
I suspect there is a good chance that the root cause of this issue has been fixed in the latest newick release (or even earlier).  Regarding testing, the method `sanitise_tree` in `configuration.py` now does the following checks on what we get back from the `newick` library:
- `assert all([len(n.descendants) in (0,2) for n in tree.walk()])` (only on starting trees, not monophyly trees)
- `assert len(tree.get_leaves()) == len(self.languages)` (starting and monophyly)
- `assert all([l.name for l in tree.get_leaves()])` (starting and monophyly)

i.e. no redundant internal nodes and exactly the right number of leaves, with all of them having a non-empty  name.  The above `asserts` should fail during the running of `starting_tree_tests.py` if `python-newick` botches any of the tree-manipulations performed in there.

Are we happy to close this now?

**Comment by Anaphory** [comment]
I think I checked it with the file I had problems with before (it's been a while).
I any case, it seems to work fine.
