### ISSUE TITLE
For CLDF data, beastling ignores features when inferring.

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#88]
When specifying all features explicitly in a file, I get one more feature than when I let beastling infer features itself. I thought this might be down to that feature being absent in the first language listed in the cldf, but I could not reproduce that assumption with a minimal example.

Until I manage further investigations: Attached zip file contains a cldf data file (made from IELex) and two xml files derived from that, using two different beastling configs. The configs differ in explicitly specifying all features (`_features`) or not.

When the `ant` feature is not explicitly added, it is ignored by beastling. Note that `ant` is not defined for indo1319, which appears as first language in the file, and is not constant.

[RomanceLanguages.zip](https://github.com/lmaurits/BEASTling/files/349758/RomanceLanguages.zip)

**Comment by lmaurits** [comment]
Actually, I think you were spot on about the problem being caused by the feature being absent in the first language.  I just committed a change so that the list of features is assembled from the attested features for each and every language in the dataset.  It seems to include `ant` now when I use `reconstruct.ini`.  Please confirm when you get a chance.

**Comment by Anaphory** [comment]
LGTM.
