### ISSUE TITLE
If the starting tree has 0-length branches, should we accept it?

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#94]
It may be that the stochastic Dollo model has problems with 0-length branches. (I'm definitely having problems with the Dollo model, so it might be due to that.) 0-length branches in the starting tree can arise when the `newick` parser splits a node with multiple children into multiple binary nodes.

What do we gain and lose from shifting nodes around slightly to remove 0-length branches?

(I assume it's not a good idea, but I want to bring it up nonetheless.)

**Comment by lmaurits** [comment]
I think that 0-length branches will not be rare in general, as they are the most common strategy for resolving polytomies to get a binary tree.  Our `newick` library does this, as you note, but so too will a lot of other things users might use to process their starting tree before feeding it to BEASTling.  Because of this, I don't think BEASTling should reject starting trees just because they contain a 0-length branch.  I would probably be happy with rejecting a starting tree in which _all_ branches had length 0, as this should be a rare case and I expect BEAST might crash on such an input (but we should probably test this and see).

If there are particular substitution models in BEAST which cannot handle even a single 0-length branch, then I think it's okay to fail in the particular cases where that model is being used.  Although maybe in that case a better solution would be to set the branch lengths to some small "epsilon" value, if this is enough to make the model happy?

As a general guiding principle, I think that when the user provides a starting tree we should do everything in our power to avoid changing it.  If it is absolutely necessary to change it in order to make BEAST run we should make the smallest change possible to achieve this and explicitly notify the user we've done so.
